ALTER TABLE borrowed_books 
MODIFY COLUMN return_date DATE DEFAULT (DATE_ADD(CURRENT_DATE, INTERVAL 1 MONTH));

ALTER TABLE books
ADD COLUMN bookUrl VARCHAR(100),
ADD COLUMN imageUrl VARCHAR(100);


ALTER TABLE books MODIFY COLUMN bookUrl VARCHAR(300);
ALTER TABLE books MODIFY COLUMN imageUrl VARCHAR(300);